name: Test and Deploy

on:
  push:
    branches:
      - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps: 
      - name: Greeting
        run: echo hello there!

  test-app:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout and clone
          uses: actions/checkout@v2.4.2
        - name: Setup PostgreSQL
          uses: Harmon758/postgresql-action@v1.0.0
          with: 
            postgresql db: test_db
            postgresql user: test_user
            postgresql password: password
        - name: Install dependencies
          run: npm install
        - name: Test App
          run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=password npm run test-app

  deploy:
    runs-on: ubuntu-latest
    needs: test-app
    steps: 
      - name: Checkout and clone
        uses: actions/checkout@v2.4.2
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

        
      